[package]
name = "ftag"
version = "0.2.0"
edition = "2021"
authors = ["Ranjeeth Mahankali <ranjeethmahankali@gmail.com>"]
description = "CLI tool for tagging and searching files. See README.md for more info."
readme = "README.md"
repository = "https://github.com/ranjeethmahankali/ftag"
license = "GPL-3.0-only"
keywords = ["file", "tag", "search", "organize", "archive"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4", features = ["cargo"] }
glob-match = "0.2"
edit = "0.1"
crossterm = "0.27.0"
ratatui = "0.26"
opener = "0.6"
# Dependencies for the GUI
egui = "0.28"
eframe = "0.28"
egui_extras = { version = "0.28", features = ["default", "all_loaders"] }

# For smaller binary size.
[profile.release]
strip = true  # Automatically strip symbols
lto = true # Link time optimization.
panic = "abort" # Don't unwind stack. Should never panic.
codegen-units = 1

# Debug info for profiling

# [profile.release]
# debug = 1
# [rust]
# debuginfo-level = 1

[[bin]]
name = "ftag"
path = "src/cli.rs"

[[bin]]
name = "ftagui"
path = "src/gui.rs"
