[package]
name = "fstore-rs"
version = "0.1.0"
edition = "2021"
authors = ["Ranjeeth Mahankali <ranjeethmahankali@gmail.com>"]
description = "CLI tool for tagging and searching files. See README.md for more info."
readme = "README.md"
repository = "https://github.com/ranjeethmahankali/fstore"
license = "GPL-3.0-only"
keywords = ["file", "tag", "search", "organize", "archive"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4", features = ["cargo"] }
glob-match = "0.2"
edit = "0.1"
# For the TUI mode.
crossterm = "0.27.0"
ratatui = "0.24.0"
opener = "0.6"

# For smaller binary size.

[profile.release]
strip = true  # Automatically strip symbols
lto = true # Link time optimization.
panic = "abort" # Don't unwind stack. Should never panic.
codegen-units = 1

# Debug info for profiling

# [profile.release]
# debug = 1
# [rust]
# debuginfo-level = 1
